### ISSUE TITLE
Difficulty in setting up libraries

### ISSUE THREAD

**Issue by emmannaemeka** [nsoranzo/sspace_basic#10]
Hi @nsoranzo I downloaded the open source SSPACE_BASIC and ran this command line

perl SSPACE_Basic.pl -l /Users/emmannaemeka/desktop/Gpm/sspace_basic-master/example/libraries_2.txt -s /Users/emmannaemeka/desktop/Gpm/sspace_basic-master/example/contigs_muc.fasta  -x 0 -m 32 -o 20 -t 0 -k 5 -a 0.70 -n 15 -p 0 -v 0 -z 0 -g 0 -T 1 -b standard_out

my libraries_2.txt  looks like this

muc1 contigs_muc.fasta 300 0.5 0.75 FR

the error returned was

ERROR: Invalid file in library muc1: contigs_muc.fasta -- fatal

As I stated earlier, what should make up my libraries. My genome sequence came in a single fasta file.

Thanks

**Comment by nsoranzo** [comment]
To run SSPACE you need at least a paired-end FASTA/Q library (i.e. 2 files) and the assembled contigs (using e.g. ABySS).
