### ISSUE TITLE
Bowtie exits with error line 341 on SSPACE v2

### ISSUE THREAD

**Issue by freuv** [nsoranzo/sspace_basic#14]
Building Bowtie index for contigs
Bowtie-build error; -1 at 
sspace_basic/bin/ExtendOrFormatContigs.pl line 341.

Any help would be much appreciated!

Line 341 for reference,

system("bowtie-build $contigFile bowtieoutput/$bowtieout --quiet --noref") == 0 || die "\nBowtie-build error; $?"; # returns exit status values

**Comment by nsoranzo** [comment]
You need to have `bowtie-build` (and `bowtie`) commands on your PATH to run `SSPACE_Basic.pl`, as explained in the README. You can verify that by running:

```shell
which bowtie-build
```

If this does not return the path of `bowtie-build`, you need to install it.
