### ISSUE TITLE
 Where can we find the contigs that form a SSPACE scaffold?

### ISSUE THREAD

**Issue by a-velt** [nsoranzo/sspace_basic#15]
Hi,

Everything is in the title, I didn't find a file to know which contigs are used to form each SSPACE-LongRead scaffold. Does this file exist ?

Best,
Amandine

**Comment by a-velt** [comment]
Hi,

Is there an answer to my question ? 

Best,
Amandine

**Comment by nsoranzo** [comment]
@a-velt Please have a look existing documentation, unfortunately as stated in the https://github.com/nsoranzo/sspace_basic/blob/master/README#L11 I cannot offer support for this software.
