### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by JFsanchezherrero** [nsoranzo/sspace_basic#7]
Hello!
I decided to try SSPACE for the scaffolding of my draft genome. I sent the command to the cluster a couple of weeks ago on my draft genome and it is still working in the contig extension. I am afraid it would take at least a couple of weeks more attending to the amount of contigs, around 6 millions.

Yesterday I was checking the code and I found, in the contig extension step, how to parallelize the process. I am checking and debugging if it is working but I guess it is going to be a great improvement for the performance.

I will share it with you once I finish the debugging but I wonder if you are interested in including this version how it could be possible to do it.

Cheers

Jose F.

**Comment by nsoranzo** [comment]
Hi @JFsanchezherrero,
if you manage to open a pull request with your changes, I can review and eventually merge it. For more info about the state of this tool, see https://github.com/nsoranzo/sspace_basic/issues/6 .

**Comment by JFsanchezherrero** [comment]
Dear @nsoranzo, 
After a long summer break I have managed to implement and pull a request for that contig extension step. 
I hope you find it interesting and you can merge it. I have tested for my own data and I have obtain great results.

Regards, 
Jose F.

**Comment by nsoranzo** [comment]
Thanks @JFsanchezherrero, I'll have look at the PR, closing this issue.
