### ISSUE TITLE
Difficulty setting up library 

### ISSUE THREAD

**Issue by emmannaemeka** [nsoranzo/sspace_basic#9]
Hi,
I am a newbie in bioinformatics. I am trying to use space to build scaffold for my sequences.

I do not understand how to set up my library

I had put together this find below

lib1 bowtie mucuna_pruriens_raw.fa 300 0.5 FR

However when I run this command 

perl /Users/emmannaemeka/desktop/GPM/SSPACE-STANDARD-3.0_linux-x86_64/SSPACE_Standard_v3.0.pl -l libraries2 -s //Users/emmannaemeka/desktop/Gpm/maker/data/mucuna/mucuna_pruriens_raw.fa -k 5 -a 0.5 -x 0 -b mucuna_scaffold_no_extention

the result is 

ERROR: Invalid (-l) library file libraries2 ...Exiting.

Please can you help me resolve it?

**Comment by nsoranzo** [comment]
This error should appear only if the path of your library file `libraries2` is not correct, which in your case means that the file is in not the directory where you've launched the command. Try to specify the full path of `libraries2`.

**Comment by emmannaemeka** [comment]
Hi


Thanks for the reply


I ran the command


perl /Users/emmannaemeka/desktop/GPM/SSPACE-STANDARD-3.0_linux-x86_64/
SSPACE_Standard_v3.0.pl -l
/Users/emmannaemeka/desktop/Gpm/SSPACE-STANDARD-3.0_linux-x86_64/example/libraries_2.txt
-s
/Users/emmannaemeka/desktop/Gpm/SSPACE-STANDARD-3.0_linux-x86_64/example/contigs_muc.fasta
-k 5 -a 0.5 -x 0 -b mucuna_scaffold_no_extention




this is the content of my library


lib1 bowtie contigs_muc.fasta 300 0.5 FR



the result was



ERROR: Invalid file in library lib1: 300 -- fatal



Can you help me on modifying the content of my library?


I don't have a mate pair for my sequence. I only have one fasta file for my
sequence so how do I create a library?




Nnadi Nnaemeka Emmanuel
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
Publications:
https://www.researchgate.net/profile/Emmanuel_Nnadi/publications
